-- 1. termsテーブルの作成
create table if not exists public.terms (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLSポリシー（必要であれば）
alter table public.terms enable row level security;
create policy "Allow public read access" on public.terms for select using (true);
create policy "Allow admin full access" on public.terms using (true);

-- 2. 初期データの投入
-- IDを明示的に指定して、既存のgeneration（数値）とマッピングしやすくします。
insert into public.terms (id, name) values 
(1, '1期'), (2, '2期'), (3, '3期'), (4, '4期'), (5, '5期'),
(6, '6期'), (7, '7期'), (8, '8期'), (9, '9期'), (10, '10期'),
(11, '11期'), (12, '12期'), (13, '13期'), (14, '14期'), (15, '15期'),
(16, '16期'), (17, '17期'), (18, '18期'), (19, '19期'), (20, '20期'),
(99, 'その他')
on conflict (id) do nothing;

-- シーケンスを更新（IDオートインクリメントが衝突しないように）
select setval('terms_id_seq', 100);

-- 3. membersテーブルへのカラム追加
alter table public.members 
add column if not exists term_id bigint references public.terms(id);

-- 4. 既存データの移行 (generation -> term_id)
update public.members 
set term_id = generation 
where term_id is null 
  and generation is not null 
  and generation <= 20; -- マスタにある範囲のみ移行

-- (任意) 移行できなかったデータの確認
-- select * from members where term_id is null;
