
-- 1. 既存の（間違った）テーブルを削除
DROP TABLE IF EXISTS app_settings;

-- 2. 正しい定義でテーブルを作成
CREATE TABLE app_settings (
  id bigint generated by default as identity primary key,
  key text unique not null,
  value jsonb
);

-- 3. 初期データの投入（これをしないとダッシュボードが空になります）
INSERT INTO app_settings (key, value) VALUES
('application_text', '"現在、各種講座のお申し込みを受付中です。"'),
('payment_links', '[]'),
('admin_email', '"info@shingengaku.com"'),
('admin_bcc_email', '""'),
('email_template', '{}'),
('email_template_general', '{}'),
('email_template_resend', '{}'),
('email_template_forgot_pass', '{}');

-- 4. 権限設定（RLS）があれば無効化（読み書き自由に）
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON app_settings FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON app_settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON app_settings FOR UPDATE USING (true);
